vpn_fortigate1:
  site:
    host: 192.168.176.137
    vdom: root
    peerIP: 192.168.176.139
    pskey: sample
    dh: 5
    proposal: des-sha512
    phase2keylifetime: 3600
    subnets:
      site_local: Local
      site_remote: Remote
      sas:
        - name: sa1
          local: 10.10.30.0 255.255.255.0
          remote: 10.10.50.0 255.255.255.0
    outbound_policy_id:
    inbound_policy_id:
    seq_num_route_static: 1

vpn_fortigate2:
  site:
    host: 192.168.176.139
    vdom: root
    peerIP: 192.168.176.137
    pskey: sample
    dh: 5
    proposal: des-sha512
    phase2keylifetime: 3600
    subnets:
      site_local: Local
      site_remote: Remote
      sas:
        - name: sa1
          local: 10.10.50.0 255.255.255.0
          remote: 10.10.30.0 255.255.255.0
    outbound_policy_id:
    inbound_policy_id:
    seq_num_route_static: 1
