---
- name: installation of awx
  hosts: ubuntu-vm

  vars:
    who_uses_awx_ui: ass-niang

  tasks:
    - name: Update and upgrade apt packages
      become: true
      apt:
        upgrade: yes
        update_cache: yes

    - name: Install the apt packages
      become: true
      apt:
        name:
          - docker.io
          - ansible
          - curl
          - nodejs
          - npm
          - python3-pip
          - git
          - pwgen
          - vim

    - name: Install python packages
      pip:
        name:
          - requests
          - docker-compose==1.23.1
        executable: pip3.10

    - name: Install pyYaml package
      pip:
        name: pyYaml
        extra_args: --upgrade

    - name: Install npm
      community.general.npm:
        name: npm
        global: true

    - name: Start and enable service docker
      service:
        name: docker
        state: started
        enabled: yes

    - name: Download docker-compose
      shell: curl -L "https://github.com/docker/compose/releases/download/1.23.1/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose

    # - name: Download docker-compose
    #   uri:
    #     url: https://github.com/docker/compose/releases/download/1.23.1/docker-compose-Linux-x86_64
    #     dest: /usr/local/bin/docker-compose

    - name: Make docker-compose file executable
      file:
        path: /usr/local/bin/docker-compose
        mode: 111

    - name: Update apt packages
      become: true
      apt:
        update_cache: yes

    # - name: Get the username
    #   command: whoami
    #   register: username

    - name: Download awx from github
      git:
        repo: https://github.com/ansible/awx.git
        dest: /home/ansible-awx/
        single_branch: yes
        version: 21.8.0

    - name: Build docker-compose with a Makefile
      make:
        chdir: /home/ansible-awx/
        target: docker-compose-build

    - name: Create the awx_ui_build.sh file
      file:
        path: '/home/{{ who_uses_awx_ui }}/Desktop/awx_ui_build.sh'
        state: touch
        owner: root
        mode: 111

    - name: Create the awx_start.sh file
      file:
        path: '/home/{{ who_uses_awx_ui }}/Desktop/awx_start.sh'
        state: touch
        owner: root
        mode: 111

    - name: Write in the awx_ui_build.sh file
      copy:
        src: 'awx_ui_build.sh'
        dest: '/home/{{ who_uses_awx_ui }}/Desktop/awx_ui_build.sh'
        owner: root
        mode: 111

    - name: Write in the awx_start.sh file
      copy:
        src: 'awx_start.sh'
        dest: '/home/{{ who_uses_awx_ui }}/Desktop/awx_start.sh'
        owner: root
        mode: 111

    # - name: Run docker-compose with a Makefile
    #   make:
    #     chdir: /home/ansible-awx/
    #     target: docker-compose

    # - name: Build AWX UI
    #   community.docker.docker_container_exec:
    #     container: tools_awx_1
    #     command: /bin/bash -c "make clean-ui ui-devel"
    
