- name: Configure fortigate
  hosts: fortigate-A

  tasks:
    - name: fetch all policies
      fortinet.fortios.fortios_configuration_fact:
        sorters: policyid
        formatters: name
        selector: firewall_policy
      register: policies

    - debug:
        var: policies.meta.results[0]
