- name: Get the status of VPN
  hosts: fortigate-A, localhost
  vars:
    - down_vpn: []
    - up_vpn: []

  tasks:
    - name: Get the vpn ipsec
      fortinet.fortios.fortios_monitor_fact:
        vdom: "root"
        selector: "vpn_ipsec"
      register: vpn
      delegate_to: fortigate-A

    - name: Get vpn with down status
      set_fact: down_vpn="{{down_vpn + [item.proxyid[0].p2name]}}"
      when: item.proxyid[0].status=="down"
      loop: "{{vpn.meta.results}}"

    - name: Get vpn with up status
      set_fact: up_vpn="{{up_vpn + [item.proxyid[0].p2name]}}"
      when: item.proxyid[0].status=="up"
      loop: "{{vpn.meta.results}}"

    - name: Remove file (delete file)
      file:
        path: "vpn_status.txt"
        state: absent
      delegate_to: localhost

    - name: Insert the date of access of the vpn status
      lineinfile:
        path: "vpn_status.txt"
        state: present
        create: true
        line: "File generated at {{ansible_date_time.time}} {{ansible_date_time.date}}"
      delegate_to: localhost

    - name: Hedear of down vpn
      lineinfile:
        path: "vpn_status.txt"
        state: present
        create: true
        line: "---- down vpn ----"
      delegate_to: localhost

    - name: Write the down vpn in the txt file
      lineinfile:
        path: "vpn_status.txt"
        state: present
        create: true
        line: "{{item}}"
      loop: "{{down_vpn}}"
      delegate_to: localhost

    - name: Hedear of up vpn
      lineinfile:
        path: "vpn_status.txt"
        state: present
        create: true
        line: "---- up vpn ----"
      delegate_to: localhost

    - name: Write the up vpn in the txt file
      lineinfile:
        path: "/home/vpn_status.txt"
        state: present
        create: true
        line: "{{item}}"
      loop: "{{up_vpn}}"
      delegate_to: localhost
