- name: Configure fortigate
  hosts: fortinet
  vars:
    never_used_policies: []

  tasks:
    - name: Get the static routes
      fortinet.fortios.fortios_configuration_fact:
        selector: "router_static"
      register: router

    - debug:
        msg: "{{router.meta.results[-1]['seq-num']}}"
