- name: Configure fortigate
  hosts: fortigate-A
  vars:
    never_used_policies: []

  tasks:
    - name: Get the statistics of the policies
      fortinet.fortios.fortios_monitor_fact:
        selector: "firewall_policy"
      register: policy

    - name: "List of never used policies"
      set_fact: never_used_policies="{{never_used_policies + [item.policyid]}}"
      when: item.last_used is undefined
      loop: "{{policy.meta.results}}"

    - name: Get the never used policies
      fortinet.fortios.fortios_configuration_fact:
        formatters: comments
        filters:
          - policyid=="{{item}}"
        selector: "firewall_policy"
      register: policies
      loop: "{{never_used_policies}}"

    - debug:
        msg: "{{item.meta.results[0].comments}}"
      loop: "{{policies.results}}"
