- name: Configure fortigate
  hosts: fortigate-A
  vars:
    policies_name:
      - "Acces-Internet"
      - "inbound-Remote-to-Local"

  tasks:
    - name: filter the policy name
      fortinet.fortios.fortios_configuration_fact:
        vdom: "root"
        filters:
          - status=="disable"
          - name=="{{item}}"
        formatters:
          - name
          - policyid
        selector: "firewall_policy"
      register: policies
      loop: "{{policies_name}}"

    - name: fail
      ansible.builtin.fail:
        msg: There is no disabled policy named "{{item.item}}".
      when: item.meta.matched_count | int == 0
      loop: "{{policies.results}}"

    - name: Enable the policies
      fortios_firewall_policy:
        vdom: root
        state: present
        firewall_policy:
          policyid: "{{item.meta.results[0].policyid}}"
          status: enable
      with_items: "{{policies.results}}"
