- name: Get the status of VPN
  hosts: "{{node}}"
  vars:
    - down_vpn: []
    - up_vpn: []

  tasks:
    - name: Get the vpn ipsec
      fortinet.fortios.fortios_monitor_fact:
        vdom: "root"
        selector: "vpn_ipsec"
      register: vpn

    - name: Get vpn with down status
      set_fact: down_vpn="{{down_vpn + [item.name]}}"
      when: item.proxyid[0].status=="down"
      loop: "{{vpn.meta.results}}"

    - name: Get vpn with up status
      set_fact: up_vpn="{{up_vpn + [item.name]}}"
      when: item.proxyid[0].status=="up"
      loop: "{{vpn.meta.results}}"

- name: Create the file
  hosts: awx_localhost
  vars:
    - up_vpn: '{{hostvars[node]["up_vpn"]}}'
    - down_vpn: '{{hostvars[node]["down_vpn"]}}'

  tasks:
    - name: Remove file (delete file)
      file:
        path: "/home/{{awx_ui_user}}/Bureau/vpn_status.txt"
        state: absent

    - name: Insert the date of access of the vpn status
      lineinfile:
        path: "/home/{{awx_ui_user}}/Bureau/vpn_status.txt"
        state: present
        create: true
        line: "File generated at {{ansible_date_time.time}} {{ansible_date_time.date}}\n\n[{{node}}]"

    - name: Hedear of down vpn
      lineinfile:
        path: "/home/{{awx_ui_user}}/Bureau/vpn_status.txt"
        state: present
        create: true
        line: "\n>> DOWN VPN:"

    - name: Write the down vpn in the txt file
      lineinfile:
        path: "/home/{{awx_ui_user}}/Bureau/vpn_status.txt"
        state: present
        create: true
        line: "\t- {{item}}"
      when: hostvars[node]["down_vpn"] is defined
      loop: "{{down_vpn}}"

    - name: Hedear of up vpn
      lineinfile:
        path: "/home/{{awx_ui_user}}/Bureau/vpn_status.txt"
        state: present
        create: true
        line: "\n>> UP VPN:"

    - name: Write the up vpn in the txt file
      lineinfile:
        path: "/home/{{awx_ui_user}}/Bureau/vpn_status.txt"
        state: present
        create: true
        line: "\t- {{item}}"
      when: hostvars[node]["up_vpn"] is defined
      loop: "{{up_vpn}}"
