---
# vars file for config-policy
policy_name: Accès Internet
destinations_address:
  - name: all
destinations_interface:
  - name: port2
policyid: 1
services:
  - name: HTTPS
  - name: HTTP
  - name: DNS
sources_address:
  - name: all
sources_interface:
  - name: port1
schedule: always
schedule_timeout: disable
