- name: fact gathering
  fortinet.fortios.fortios_monitor_fact:
    selector: "firewall_policy"
  register: policy

- name: Disable a policy
  fortios_firewall_policy:
    vdom: root
    state: present
    firewall_policy:
      policyid: "{{item.policyid}}"
      status: disable
  when:
    - item.policyid | int > 0
    - years | int + months | int + days | int + hours | int + minutes | int + secondes | int > 0
    - item.last_used is undefined or (ansible_date_time.epoch | int - item.last_used | int)  > (years | int * 3600*24*365 + months | int * 3600*24*30 + days | int * 3600*24 + hours | int * 3600 + minutes | int * 60 + secondes | int)
  with_items: "{{policy.meta.results}}"
