---
# tasks file for disable-policy
- name: fact gathering
  fortios_monitor_fact:
    selector: 'firewall_policy'
    params:
        policyid: '1'
  register: policy

- debug:
    var: policy

- set_fact: last_used="{{policy.meta.results[0].last_used | int}}"
    threshold="{{years * 3600*24*365 + months * 3600*24*30 + days * 3600*24 + hours * 3600 + minutes * 60 + secondes}}"
  when: policy.meta.results[0].last_used is defined

- debug:
    var:  threshold

- debug:
    var:  ansible_date_time.epoch | int - last_used | int

- name: Disable a policy
  fortios_firewall_policy:
    vdom: root
    state: present
    firewall_policy:
      policyid: 1
      status: disable
  when: 
    - threshold > 0
    - policy.meta.results[0].last_used is undefined or (ansible_date_time.epoch | int - last_used | int)  > (threshold | int)
    