---
# tasks file for config-globales
- name: "Configuration globale des fortigates"
  fortios_system_global:
    vdom: root
    system_global:
      admin_concurrent: enable
      admin_console_timeout: 300
      admin_https_redirect: disable
      admin_login_max: 100
      admin_maintainer: enable
      admin_port: 80
      admin_restrict_local: disable
      admin_scp: disable
      admin_server_cert: Fortinet_GUI_Server
      admin_sport: 443
      admin_ssh_grace_time: 120
      admin_ssh_password: enable
      admin_ssh_port: 22
      admin_telnet: enable
      admin_telnet_port: 23
      admintimeout: 120
      gui_date_format: dd/MM/yyyy
      gui_date_time_source: system
      #post_login_banner: enable
      hostname: "{{ inventory_hostname }}"
      timezone: 80
      language: english
      gui_firmware_upgrade_warning: enable
